# Generated by Django 4.2.4 on 2023-08-28 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('IMPORTANT', 'IMPORTANT'), ('MODERATE', 'MODERATE')], default='MODERATE', max_length=50)),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING')], default='PENDING', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
